### PR TITLE
Add builder nodes to tt-mlir CI

### PR DESCRIPTION
**Pull request by vmilosevic**
Set up and register new builder machines for Github CI. These machines perform build and lint tasks 2x faster than standard silicon runners. 

- install docker on bileder VMs
- register builder nodes as Github self-hosted runners
- add them to tt-mlir project
- tag them with "builder" label
- update CI workflow to use "builder" nodes

### CODE REVIEW

**Review by tapspatel — APPROVED** [review]

**Comment by tapspatel** [comment]
looks good!

**Comment by tapspatel** [comment]
actually, since this is working now, we can also change the self hosted in https://github.com/tenstorrent/tt-mlir/blob/main/.github/workflows/build-and-test.yml to builder

**Comment by tapspatel** [comment]
I changed it on my branch in this PR: https://github.com/tenstorrent/tt-mlir/actions/runs/10600240062/job/29377224992

**Comment by nsmithtt** [comment]
@vmilosevic, I have some concerns about throughput here.  Currently our build does take 40 min, but we have kind of have unlimited GitHub runners, so no matter how many PRs are in flight it's a pretty consistent turnaround.

If we have our own builders, even if they are 2x as fast, with enough PRs we can clog the whole system which is what we saw in Buda.  The 40 min build is honestly not that bad, I'd somewhat prefer continuing to use GitHub for our builders to maintain throughput.

**Review by nsmithtt — APPROVED** [review]

**Pull request merged**
