### PR TITLE
Added Enums, Ops, Attrs for TTNN Dialect to Python Bindings

### PR DESCRIPTION
**Pull request by vprajapati-tt**
- Generated Enums, Ops
- Manually defined Attrs through CAPI.
- Addresses #941 :)

### CODE REVIEW

**Review by odjuricicTT — COMMENTED** [review]
Looks good! Tho, i don't think we need all of these attrs exposed for tt-explorer?

**Comment by vprajapati-tt** [comment]
> Looks good! Tho, i don't think we need all of these attrs exposed for tt-explorer?

Yeah, I thought to add them as I was already exposing the bindings.

**Comment by nsmithtt** [comment]
> > Looks good! Tho, i don't think we need all of these attrs exposed for tt-explorer?
> 
> Yeah, I thought to add them as I was already exposing the bindings.

Agreed, it doesn't hurt to have them, might be useful for testing/scripting in the future.

**Comment by vprajapati-tt** [comment]
Rebased from `nsmith/static` apologies for all the pings 😅

**Review by nobradovictt — APPROVED** [review]

**Review by nsmithtt — APPROVED** [review]

**Pull request merged**
