### PR TITLE
Allow scalar types to propogate through runtime.

### LINKED ISSUE #554: Add support for scalar inputs in TTNN
Providing TTNN an input with scalars results in following assertion failure: 

`Tensor tt::runtime::createTensor(std::shared_ptr<void>, const std::vector<std::uint32_t> &, const std::vector<std::uint32_t> &, std::uint32_t, ::tt::target::DataType): Assertion `not shape.empty()' failed. `

The following TTIR input was used to generate the above error: 

```
TTIR Module
module @jit_convert_element_type attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<f32> {mhlo.layout_mode = "default"}) -> (tensor<f32> {jax.result_info = "", mhlo.layout_mode = "default"}) {
    return %arg0 : tensor<f32>
  }
}
```

### PR DESCRIPTION
**Pull request by uazizTT**
Fixes #554

### CODE REVIEW

**Comment by sdjordjevicTT** [comment]
@nsmithtt FYI
Not sure how feasible it is, but maybe we should do something similar for scalars as we did for 1D tensors?

**Comment by uazizTT** [comment]
I think there is a fundamental question, do we treat scalars as 1d tensor or keep them as scalars throughout the pipeline? 

If it is the former, then how do we differentiate between 1d tensor and scalars? 

The above solution might not be elegant but keeps the values are scalars throughout the pipeline.

**Comment by uazizTT** [comment]
For reference, this is what the outputs for each stage looks like: 

**VHLO Module**
```
module @jit_convert_element_type attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  vhlo.func_v1 @main(%arg0: !vhlo.tensor_v1<!vhlo.f32_v1>) -> (!vhlo.tensor_v1<!vhlo.f32_v1>) {
    "vhlo.return_v1"(%arg0) : (!vhlo.tensor_v1<!vhlo.f32_v1>) -> ()
  } {arg_attrs = #vhlo.array_v1<[#vhlo.dict_v1<{#vhlo.string_v1<"mhlo.layout_mode"> = #vhlo.string_v1<"default">}>]>, res_attrs = #vhlo.array_v1<[#vhlo.dict_v1<{#vhlo.string_v1<"jax.result_info"> = #vhlo.string_v1<"">, #vhlo.string_v1<"mhlo.layout_mode"> = #vhlo.string_v1<"default">}>]>, sym_visibility = #vhlo.string_v1<"public">}
}

```
**TTIR Module**
```
module @jit_convert_element_type attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<f32> {mhlo.layout_mode = "default"}) -> (tensor<f32> {jax.result_info = "", mhlo.layout_mode = "default"}) {
    return %arg0 : tensor<f32>
  }
}

```
**TTIR Runtime Module**
```
module @jit_convert_element_type attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32, tt.device = #tt.device<#tt.grid<8x8, (d0, d1) -> (0, d0, d1)>, [0]>, tt.system_desc = #tt.system_desc<[{arch = <wormhole_b0>, grid = 8x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, l1_unreserved_base = 0, erisc_l1_unreserved_base = 0, dram_unreserved_base = 0, physical_cores = {worker = [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)] dram = [(8, 0), (9, 0), (10, 0), (8, 1), (9, 1), (10, 1), (8, 2), (9, 2), (10, 2), (8, 3), (9, 3), (10, 3)]}, supported_data_types = [<f32>, <f16>, <bf16>, <bfp_f8>, <bfp_bf8>, <bfp_f4>, <bfp_bf4>, <bfp_f2>, <bfp_bf2>, <u32>, <u16>, <u8>], supported_tile_sizes = [(4 x 16), (16 x 16), (32 x 16), (4 x 32), (16 x 32), (32 x 32)]}], [0], [3 : i32], [<0, 0, 0, 0>]>} {
  func.func public @main(%arg0: tensor<f32, #tt.layout<() -> (0, 0), undef, <1x1>, memref<1x1xf32, #tt.memory_space<system>>>> {mhlo.layout_mode = "default"}) -> (tensor<f32, #tt.layout<() -> (0, 0), undef, <1x1>, memref<1x1xf32, #tt.memory_space<system>>>> {jax.result_info = "", mhlo.layout_mode = "default"}) {
    %0 = "ttnn.open_device"() <{device_ids = [0]}> : () -> !tt.device<<#tt.grid<8x8, (d0, d1) -> (0, d0, d1)>, [0]>>
    "ttnn.close_device"(%0) : (!tt.device<<#tt.grid<8x8, (d0, d1) -> (0, d0, d1)>, [0]>>) -> ()
    return %arg0 : tensor<f32, #tt.layout<() -> (0, 0), undef, <1x1>, memref<1x1xf32, #tt.memory_space<system>>>>
  }
}
```

**Comment by nsmithtt** [comment]
Yeah I agree with @sdjordjevicTT, I think this should just be a strict type conversion to a 1d tensor.  The runtime is going to give us tensors, so there will be some contract there where it's expected that the runtime wraps the scalar in a runtime tensor.  This is required from the runtime side anyway, there is no other type to pass in.

**Comment by nsmithtt** [comment]
We should be able to do this in `StableHLOToTTIR.cpp`, it's just a new case for `typeConverter` declared on line 75.  We should just add a conversion that matches their scalar type and just picks the corresponding tensor type and make it 1d.

**Comment by uazizTT** [comment]
Ok got it, so we keep it as 1d tensor, yeah I think it can be done in `StableHLOToTTIR.cpp`, let me try. Thanks all.

**Pull request closed without merging**
