### PR TITLE
#475: Create a whls release for ttrt

### PR DESCRIPTION
**Pull request by tapspatel**

### CODE REVIEW

**Review by nsmithtt — COMMENTED** [review]
Looks great! Thanks Taps.

One thing I think we need to update now though is `get_ttmetal_home_path`, shouldn't that point to the copied metal files installed inside of the wheel?  Probably could use some relative path from `os.path.realpath(__file__)`

**Comment by nsmithtt** [comment]
Potentially `get_ttmlir_home_path` variable too? Do we need this one? If we can get rid of another env that'd be great, the only usage I could see is to get to tracy things, but that seems like it could use `get_ttmetal_home_path` instead.

**Review by nsmithtt — APPROVED** [review]
Awesome!

**Comment by tapspatel** [comment]
removed all paths, tested on fresh new machine with new docker image. Works as intended

**Pull request merged**
