### PR TITLE
Removed duplicate TensorMemoryLayout enum

### PR DESCRIPTION
**Pull request by LPanosTT**
Removed duplicate TensorMemoryLayout enum

### CODE REVIEW

**Review by nsmithtt — CHANGES_REQUESTED** [review]
Hey @LPanosTT, per slack discussion lmk if this is still needed.  I think we would like to keep the TTNN enum.  After some of the refactoring work from #701 lands I think we actually want to remove `TT_TensorMemoryLayoutAttr`.

**Comment by LPanosTT** [comment]
@nsmithtt yeah I’ll keep this open for now

**Comment by nsmithtt** [comment]
> @nsmithtt yeah I’ll keep this open for now

I think we want `TTNN_TensorMemoryLayoutAttr` enum though.

**Comment by svuckovicTT** [comment]
Hey Lewis, this enum is *not* a duplicate. It was intentionally added to model the TTNN API, in which there is no `None` value for the enum.

If we were to use the TT dialect enum which has the `None` value, we'd need to handle it in many places within the TTNN dialect and any downstream dialects/runtimes - that would not be the greatest of practices.

**Pull request closed without merging**
