### PR TITLE
Add missing codeowner dirs

### PR DESCRIPTION
**Pull request by nsmithtt**

### CODE REVIEW

**Comment by nsmithtt** [comment]
@svuckovicTT, let me know if you're OK with owning the whole tools dir.  I realized we had some missing code owner coverage, i.e. docs + readme + env.

**Review by nobradovictt — APPROVED** [review]

**Comment by svuckovicTT** [comment]
> @svuckovicTT, let me know if you're OK with owning the whole tools dir. I realized we had some missing code owner coverage, i.e. docs + readme + env.

Sure! I think it'd also be good to add at least 1 more person (ideally 2) so that everything runs smoothly during PTOs, etc.

**Review by svuckovicTT — APPROVED** [review]

**Review by sdjordjevicTT — APPROVED** [review]

**Comment by svuckovicTT** [comment]
@nsmithtt not sure if intentional, but you didn't merge this :)

**Comment by nsmithtt** [comment]
> @nsmithtt not sure if intentional, but you didn't merge this :)

Thank you! I updated the PR

**Pull request merged**
