### PR TITLE
eltwise_max fix: add copy_tile_init() needed before operand moves to DST

### PR DESCRIPTION
**Pull request by vroubtsovTT**
- the code prefix that prepares operands for max_tile() now contains copy_tile_init() that was missing from my original impl
- the original simple_max.mlir testcase has been restored

I have reproduced the buggy behavior seen by Kyle locally/in CI and subsequently saw it disappear after the above fix.

### CODE REVIEW

**Comment by vroubtsovTT** [comment]
the metal call now emitted is bolded here:

    for (int32_t v18 = v14; v18 < v15; v18 += v16) {
      int32_t v19 = v17;
      int32_t v20 = 0;
      int32_t v21 = 1;
      tile_regs_acquire();
      **copy_tile_init();**
      copy_tile(v2, v19, v20);
      copy_tile(v4, v19, v21);
      max_tile(v20, v21);
      tile_regs_commit();
      tile_regs_wait();
      pack_tile(v20, v6, v19);
      tile_regs_release();
      int32_t v22 = 1;
      int32_t v23 = v19 + v22;
      v17 = v23;
    };

**Comment by vroubtsovTT** [comment]
emitted code now looks like this (fixed line in bold):

    for (int32_t v18 = v14; v18 < v15; v18 += v16) {
      int32_t v19 = v17;
      int32_t v20 = 0;
      int32_t v21 = 1;
      tile_regs_acquire();
      **copy_tile_init();**
      copy_tile(v2, v19, v20);
      copy_tile(v4, v19, v21);
      max_tile(v20, v21);
      tile_regs_commit();
      tile_regs_wait();
      pack_tile(v20, v6, v19);
      tile_regs_release();
      int32_t v22 = 1;
      int32_t v23 = v19 + v22;
      v17 = v23;
    };
```

**Review by kmabeeTT — COMMENTED** [review]
Wow nice turnaround, Vlad!

**Review by kmabeeTT — APPROVED** [review]

**Review by nsmithtt — APPROVED** [review]
Thanks Vlad!

**Comment by vroubtsovTT** [comment]
closes #1491

**Pull request merged**
