### PR TITLE
Adjust optimizer team codeowners

### PR DESCRIPTION
**Pull request by odjuricicTT**
1. Add additional codeowners for optimizer components to account for Nikola leaving.
2. Add ownership of TTNN Interface implementation.
3. Add two more people to own the CODEOWNERS file itself to have more redundancy.

### CODE REVIEW

**Comment by odjuricicTT** [comment]
@mbezuljTT Please check if i missed anything from your side?

**Review by vcanicTT — APPROVED** [review]

**Comment by mbezuljTT** [comment]
> @mbezuljTT Please check if i missed anything from your side?

All good from my side, thanks for the ping

**Review by mbezuljTT — APPROVED** [review]
All good from my side. 

just curious - why you haven't removed  @nobradovictt from the owners file?

**Comment by odjuricicTT** [comment]
> just curious - why you haven't removed @nobradovictt from the owners file?

I'd prefer to remove him after he has officially left the company. Right now he is on PTO.

**Review by sdjordjevicTT — APPROVED** [review]
Looks good, thanks!

**Comment by tt-mpantic** [comment]
Can you add me to CODEOWNERS file too ?

**Review by tt-mpantic — APPROVED** [review]

**Review by vmilosevic — APPROVED** [review]

**Pull request merged**
