### PR TITLE
Remove ttnn open/close device

### PR DESCRIPTION
**Pull request by nsmithtt**
These ops are somewhat confusing and are also not observed by the TTNN runtime.  Device creation is handled externally by the runtime user and expected to persist before and after program execution.  It doesn't make sense for the compiler to manage device open/close so removing these ops.

### CODE REVIEW

**Review by jnie-TT — APPROVED** [review]

**Review by nobradovictt — APPROVED** [review]
Less is more! :)

**Comment by svuckovicTT** [comment]
Hey @nsmithtt, thanks for pinging me on Slack, I'll continue the talk here.

I like the simplification (who doesn't?!), but my concern is that this will disallow us to model some ttnn calls that require a device as an argument. ttnn lib ops like `ttnn::to_layout()` and `ttnn::to_device()` require a device to be supplied, which means that all the "forward" signatures in MLIR should have a device as an argument.

Are there scenarios where we might have multiple device/device_mesh objects? If so, I think TTIR should match the devices to ops/tensors so that TTNN can know how to handle these cases.

**Comment by nsmithtt** [comment]
> I like the simplification (who doesn't?!), but my concern is that this will disallow us to model some ttnn calls that require a device as an argument. ttnn lib ops like `ttnn::to_layout()` and `ttnn::to_device()` require a device to be supplied, which means that all the "forward" signatures in MLIR should have a device as an argument.
>
> Are there scenarios where we might have multiple device/device_mesh objects? If so, I think TTIR should match the devices to ops/tensors so that TTNN can know how to handle these cases.

Yeah I've been thinking a bit about this, I think it will be better to eventually create new ops like `get_device()` or `get_device_view(DeviceMeshView view)`.  The issue is that right now there are only 2 ops (full and empty) that actually use the opened device, everything else just implicitly uses the runtime created device which is a bit confusing.  It's additionally confusing that open/close device ops don't actually do anything so these ops are just kind of there and are misleading.

I think our current plan should be:
- Remove open/close device wholesale for now
- For multi-device we can incrementally divide the work into 2 stages:
  - For data parallel we can actually get pretty far without any new device API.  We just need something as part of the flatbuffer that tells the runtime what the topology of the device mesh is, and that's all you get for the entire program.
  - For pipeline parallel, we need to introduce some API like `get_device_view` which will take a subset view of the entire mesh and then we will need to actually observe these device views as values and track them in the runtime.

Let me know what you think.

**Comment by svuckovicTT** [comment]
> there are only 2 ops (full and empty) that actually use the opened device as part of the dialect spec

This is the situation today, but that's only because the dialect is incomplete in its current state.

In #624, I've added another 2 ops (to_layout, to_device) that need device as param.

I don't think we should merge this change until without a backup mechanism to get the device, as it'll "break" the dialect.

**Comment by nsmithtt** [comment]
> > there are only 2 ops (full and empty) that actually use the opened device as part of the dialect spec
> 
> This is the situation today, but that's only because the dialect is incomplete in its current state.
> 
> In #624, I've added another 2 ops (to_layout, to_device) that need device as param.
> 
> I don't think we should merge this change until without a backup mechanism to get the device, as it'll "break" the dialect.

Ok, I can replace `open_device` with `get_device`, does that work?

**Comment by svuckovicTT** [comment]
> > > there are only 2 ops (full and empty) that actually use the opened device as part of the dialect spec
> > 
> > 
> > This is the situation today, but that's only because the dialect is incomplete in its current state.
> > In #624, I've added another 2 ops (to_layout, to_device) that need device as param.
> > I don't think we should merge this change until without a backup mechanism to get the device, as it'll "break" the dialect.
> 
> Ok, I can replace `open_device` with `get_device`, does that work?

Yup, that should work, thank you!

**Review by svuckovicTT — APPROVED** [review]

**Review by jnie-TT — APPROVED** [review]

**Pull request merged**
