### PR TITLE
Add CPUDesc to SysDesc #1271

### PR DESCRIPTION
**Pull request by vwellsTT**
WIP

### CODE REVIEW

**Comment by nsmithtt** [comment]
😎

**Comment by tapspatel** [comment]
looking good! BTW, if its still wip, you can make it a draft PR until you are ready for review. Reason being it will run silicon pipelines even if you are not ready for it to get checked :)

**Comment by tapspatel** [comment]
on second check, draft PR doesn't stop pipeline runs. Do you mind closing the PR until you are ready for review?

**Comment by tapspatel** [comment]
closing PR

**Pull request closed without merging**
