### PR TITLE
Uplift metal to include TTNN changes for SliceOp

### PR DESCRIPTION
**Pull request by jserbedzijaTT**
In order to support the slice operation in mlir, I have to uplift metal to get the latest changes made to the slice op interface in TTNN.

### CODE REVIEW

**Comment by nvukobratTT** [comment]
@vmilosevic @jserbedzijaTT are we testing FFE as well? At least build + sanity test :))

**Review by mtopalovicTT — APPROVED** [review]

**Comment by jserbedzijaTT** [comment]
> @vmilosevic @jserbedzijaTT are we testing FFE as well? At least build + sanity test :))

**Comment by jserbedzijaTT** [comment]
> @vmilosevic @jserbedzijaTT are we testing FFE as well? At least build + sanity test :))

As far as I know, there is currently no CI job testing it out. I will do it manually. @vmilosevic , do you know if there is any effort to add this job to the MLIR CI?

**Comment by nsmithtt** [comment]
@jserbedzijaTT, yes we want to start adopting this process:
1. Uplift tt-metal in tt-mlir, get green CI
2. Uplift tt-forge-fe to the hash on this PR, get green CI there
3. Post link here to green CI from tt-forge-fe and merge

**Comment by jserbedzijaTT** [comment]
> @jserbedzijaTT, yes we want to start adopting this process:
> 
> 1. Uplift tt-metal in tt-mlir, get green CI
> 2. Uplift tt-forge-fe to the hash on this PR, get green CI there
> 3. Post link here to green CI from tt-forge-fe and merge

Should I only merge changes in the mlir project? Also, Is there an easier way to test forge CI instead of making a pull request?

**Comment by jnie-TT** [comment]
@jserbedzijaTT can we include this commit as well in the uplift: [f32e03369d606fff8ba752bfcc95e526b758062e](https://github.com/tenstorrent/tt-metal/commit/f32e03369d606fff8ba752bfcc95e526b758062e)? This fixes some reshape issues we're hitting in the ttnn backend. 

CC: @AleksKnezevic @mrakitaTT

**Comment by nsmithtt** [comment]
> Should I only merge changes in the mlir project? 

Merge in 2 stages:
- Once both projects have green CI, i.e. forge-fe get's the green with uplifted tt-mlir, we merge this PR into tt-mlir main
- Update the tt-forge-fe PR to point to the commit on tt-mlir main, and get green again, then merge into tt-forge-fe main.

> Also, is there an easier way to test forge CI instead of making a pull request?

Unfortunately there is not.

**Comment by tapspatel** [comment]
little late to this thread, but is there a reason we are not updating to tip of metal? the tag in this commit seems to be from sept 20th.

**Comment by jserbedzijaTT** [comment]
> little late to this thread, but is there a reason we are not updating to tip of metal? the tag in this commit seems to be from sept 20th.

I will merge this as is because I need it to implement the slice op, but in parallel, I will open a new pull request to update metal to the latest main.

**Comment by jserbedzijaTT** [comment]
Forge CI link: https://github.com/tenstorrent/tt-forge-fe/actions/runs/11218480537?pr=377

**Review by nsmithtt — APPROVED** [review]

**Pull request merged**
