### PR TITLE
Remove operand_constraints from generic op

### PR DESCRIPTION
**Pull request by jserbedzijaTT**
As described  in [Remove TTIR operand constraints](https://github.com/tenstorrent/tt-mlir/pulls?q=is%3Apr+is%3Aclosed+author%3AjserbedzijaTT), the removal of operand_constraints from the generic op was left incomplete. This PR finalizes that task.

Closes https://github.com/tenstorrent/tt-mlir/issues/1139

### CODE REVIEW

**Review by nsmithtt — APPROVED** [review]
Thank you!  Can we get rid of `OperandConstraintArrayAttr` in tablegen?  Or are there remaining places that still need removal?

**Comment by jserbedzijaTT** [comment]
> Thank you! Can we get rid of `OperandConstraintArrayAttr` in tablegen? Or are there remaining places that still need removal?

Sure, it should be deleted from the whole project now.

**Review by sdjordjevicTT — APPROVED** [review]
Great change, thanks Joco!

**Comment by nsmithtt** [comment]
Some straggling tests:

```
RUN: at line 1: /__w/tt-mlir/tt-mlir/build/bin/ttmlir-opt --ttir-to-ttnn-backend-pipeline="system-desc-path=" /__w/tt-mlir/tt-mlir/test/ttmlir/Silicon/TTNN/ones.mlir > /__w/tt-mlir/tt-mlir/build/test/ttmlir/Silicon/TTNN/Output/ones.mlir.tmp.mlir
+ /__w/tt-mlir/tt-mlir/build/bin/ttmlir-opt --ttir-to-ttnn-backend-pipeline=system-desc-path= /__w/tt-mlir/tt-mlir/test/ttmlir/Silicon/TTNN/ones.mlir
/__w/tt-mlir/tt-mlir/test/ttmlir/Silicon/TTNN/ones.mlir:5:19: error: unknown attribute `operand_constraint` in dialect `tt`
#any_device = #tt.operand_constraint<dram|l1|scalar|tile|any_device|any_device_tile>
```

**Pull request merged**
