### PR TITLE
Bringup reduction silicon tests that were previously unsupported

### PR DESCRIPTION
**Pull request by jnie-TT**
We're using reduction and eltwise maximum ops in tt-xla FE but didn't have silicon tests for them, so we should bring them up.

### CODE REVIEW

**Comment by mrakitaTT** [comment]
@AleksKnezevic These tests will pass because `keep_dim=True`. The issue we have in #805 is that StableHLO reduce always kills the reducing dim, so I've used `keep_dim=False` in conversion, not knowing that Metal doesn't support that configuration yet. I am now trying some solution with ReduceOp with `keep_dim=True` and then ReshapeOp afterwards to manually kill the reducing dim, because otherwise the rest of the graph would be impacted.

@jnie-TT Thanks for adding more test cases! I've added `test/ttmlir/Dialect/TTNN/simple_sum.mlir`, `test/ttmlir/Dialect/TTNN/simple_maximum.mlir` and `test/ttmlir/Dialect/TTNN/simple_max.mlir` to cover these. It is weird that `test/ttmlir/Dialect/TTNN/simple_max.mlir` is not failing in CI since I've used `keep_dim=False` in that test O.o You can remove that one too, I'll add specific test for StableHLO conversion when I fix #805, but it would be good to know why it wasn't run in CI.

P.S. I've finally went through setting up a silicon machine because I'll need it for XLA, so going forward I'll manually test everything and not rely on CI.

**Comment by jnie-TT** [comment]
> @AleksKnezevic These tests will pass because `keep_dim=True`. The issue we have in #805 is that StableHLO reduce always kills the reducing dim, so I've used `keep_dim=False` in conversion, not knowing that Metal doesn't support that configuration yet. I am now trying some solution with ReduceOp with `keep_dim=True` and then ReshapeOp afterwards to manually kill the reducing dim, because otherwise the rest of the graph would be impacted.
> 
> @jnie-TT Thanks for adding more test cases! I've added `test/ttmlir/Dialect/TTNN/simple_sum.mlir`, `test/ttmlir/Dialect/TTNN/simple_maximum.mlir` and `test/ttmlir/Dialect/TTNN/simple_max.mlir` to cover these. It is weird that `test/ttmlir/Dialect/TTNN/simple_max.mlir` is not failing in CI since I've used `keep_dim=False` in that test O.o You can remove that one too, I'll add specific test for StableHLO conversion when I fix #805, but it would be good to know why it wasn't run in CI.
> 
> P.S. I've finally went through setting up a silicon machine because I'll need it for XLA, so going forward I'll manually test everything and not rely on CI.

@mrakitaTT please note that if you want a test to run on silicon, you need to add it under the Silicon folder. Adding it under the dialect folder will only test the compiler's ability to compile a specific mlir module.

**Comment by mrakitaTT** [comment]
> @mrakitaTT please note that if you want a test to run on silicon, you need to add it under the Silicon folder. Adding it under the dialect folder will only test the compiler's ability to compile a specific mlir module, but will not generate a flatbuffer for execution on Silicon.

@jnie-TT Ohh, got it, thanks Jackson!

**Comment by jnie-TT** [comment]
I'll merge this in now since we want any future CI to be running these.

**Pull request merged**
