### PR TITLE
#483: Create release packages for ttmlir with ttrt artifacts

### PR DESCRIPTION
**Pull request by tapspatel**

### CODE REVIEW

**Comment by tapspatel** [comment]
Pending merge of: https://github.com/tenstorrent/tt-mlir/pull/476

**Comment by nsmithtt** [comment]
How frequently does the release package pipeline run?  We haven't made any mlir releases yet, I'm not sure it makes sense to release ttrt separately.

Also, I think we were planning on making releases as part of the tt-forge Monorepo, lmk if this is solving something else.

**Comment by tapspatel** [comment]
this is setup to run on every commit to main. I just needed a way to release the whls in the repo itself (so if someone wants to download it separately, they can). Else, we can keep the whls exclusive for CI. Not sure if there's another way to release it to folks

**Comment by tapspatel** [comment]
not allowed to publish just yet. Closing PR

**Pull request closed without merging**
