### PR TITLE
Add none type chip capability handling

### PR DESCRIPTION
**Pull request by jnie-TT**
#380 
Add handling for None type chip capability

### CODE REVIEW

**Review by kmabeeTT — APPROVED** [review]
LGTM! Thanks!

**Comment by kmabeeTT** [comment]
Sorry, I deleted my prev reply - I thought there was an issue (seg fault) but I had typo on my cmd (referencing wrong workspace systemdesc). Works good, no more error seen.  This looks a bit strange though, is it intended?

```
    "chip_capabilities": [
      6,
      "None"
    ],

```

**Comment by jnie-TT** [comment]
> Sorry, I deleted my prev reply - I thought there was an issue (seg fault) but I had typo on my cmd (referencing wrong workspace systemdesc). Works good, no more error seen. This looks a bit strange though, is it intended?
> 
> ```
>     "chip_capabilities": [
>       6,
>       "None"
>     ],
> ```
> 
> Edit: Maybe lets keep this open a bit to get Nick's thoughts. Edit2: chatgpt says this bitflag enum should yield values 0,1,3 but we are seeing 6 above for some reason...
> 
> ```
> enum ChipCapability: uint32 (bit_flags) {
>   None = 0,
>   PCIE = 1,
>   HostMMIO = 2,
> }
> ```

You're seeing 6 because with this change you're bitwise or'ing 0b'10 and 0b'100 so it yields 6. If the error went away then we should keep it the way it was. Since it's a bit flag the case 0 should implicitly be handled, I'll close this merge request and issue.

**Comment by svuckovicTT** [comment]
Curious, what's the use of the `None` type?

**Comment by jnie-TT** [comment]
> Curious, what's the use of the `None` type?

Remote chips connected via ethernet.

**Comment by svuckovicTT** [comment]
> > Curious, what's the use of the `None` type?
> 
> Remote chips connected via ethernet.

Would it be plausible to call it something like `TT_ChipCapabilityEth`?

**Comment by jnie-TT** [comment]
> > > Curious, what's the use of the `None` type?
> > 
> > 
> > Remote chips connected via ethernet.
> 
> Would it be plausible to call it something like `TT_ChipCapabilityEth`?

Yeah that's a good idea! I'll update the name

**Comment by nsmithtt** [comment]
+1 for adding an eth attribute.

But back to the core issue, does it work instead of using `<` and `>` to use `[` and `]`.  Or we could do this instead:
```
let assemblyFormat = "`<` (`none` `:` $value^)? `>`";
```

**Review by nsmithtt — CHANGES_REQUESTED** [review]
Let's try and support the assembly syntax I posted above.  I'd rather not have a special case value for None I think that only works around the issue.

**Comment by nsmithtt** [comment]
@jnie-TT, we can close this, fixed with #402 right?

**Comment by jnie-TT** [comment]
@nsmithtt that's correct, closing this.

**Pull request closed without merging**
