### PR TITLE
Update dependencies list on docs for building on macOS

### PR DESCRIPTION
**Pull request by madcampos**
When building on macOS from a blank state, there are some extra dependencies that were not listed (`doxygen` and `graphviz`).

This adds the dependencies and how to install them to the docs.

### CODE REVIEW

**Comment by nsmithtt** [comment]
Thanks @madcampos, do you mind moving these instructions to the Docs build section of the same document? Just as a bullet item next to the `mdbook` requirement bullet.  These deps are only needed if you want to build the docs locally which typically you won't ever need to.

**Comment by madcampos** [comment]
@nsmithtt interesting... The compilation process complained about the missing dependencies when I tried building, even without specifying anything about building the docs.

For reference, here is the list of commands I ran:
```shell
brew install cmake ninja
git clone https://github.com/tenstorrent/tt-mlir.git
cd tt-mlir/
sudo mkdir -p /opt/ttmlir-toolchain
sudo chown -R $USER /opt/ttmlir-toolchain/
source env/activate
cmake -B env/build env
cmake --build env/build
source env/activate
cmake --build build -- check-ttmlir
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DTTMLIR_ENABLE_RUNTIME=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
brew search doxygen
brew install doxygen
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DTTMLIR_ENABLE_RUNTIME=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
doxygen
brew search graphviz
brew install graphviz
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DTTMLIR_ENABLE_RUNTIME=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
```

I will move the references to the docs build section 😊

**Comment by madcampos** [comment]
Hi @nsmithtt, I've updated the docs, see if it is makes sense based on your feedback.

**Review by nsmithtt — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
